gateway:
  excludedPaths:
    - "/public"
    - "/health"
    - "/api/portal/register"
  sgPortalURL: "http://localhost:8080/token/validate"
  keyFile: "/home/jayesh/development/Softgen/sg-gateway/.backup/keystore.json"
  services:
    bmrm: "http://127.0.0.1:5000"
    sg_portal: "http://localhost:8080"
    tally_sync: "http://127.0.0.1:8082"
